again

diff --git a/.github/workflows/deploy-login.yml b/.github/workflows/deploy-login.yml
--- a/.github/workflows/deploy-login.yml
+++ b/.github/workflows/deploy-login.yml
@@ -54,6 +54,40 @@ jobs:
               -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
               ${{ secrets.DOCKER_USERNAME }}/login-service
 
+      - name: Build and push register image
+        uses: docker/build-push-action@v4
+        with:
+          context: ./BackEnd/Domains/Users/
+          file: ./BackEnd/Domains/Users/Register/Dockerfile
+          push: true
+          tags: ${{ secrets.DOCKER_USERNAME }}/register-service:latest
+
+      - name: Executing remote ssh on EC2 server for register
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.DNS_REGISTER }}
+          username: ${{ secrets.EC2_USER_UB }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            # Install Docker if it's not installed
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing Docker..."
+              sudo apt-get update -y
+              sudo apt-get install -y docker.io
+              sudo systemctl start docker
+              sudo systemctl enable docker
+            fi
+            # Stop and remove existing container if exists
+            sudo docker stop register-service || echo "No existing process found"
+            sudo docker rm register-service || echo "No existing process found"
+            # Pull and run the latest image
+            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/register-service:latest
+            sudo docker run -d -p 3004:3004 --name login-service \
+              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
+              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
+              ${{ secrets.DOCKER_USERNAME }}/register-service
+
       - name: Build and push Validate image
         uses: docker/build-push-action@v4
         with:
